
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gymDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1978lm
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: alexavram3214/websitegym:latest
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=gymDb;Username=postgres;Password=1978lm

volumes:
  db_data:
