name: CI

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and test your application
      # For Docker-based projects, you might build and push Docker images, run tests, etc.
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t websitegym:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push websitegym:latest
